### ISSUE TITLE
Hides all the tabs

### ISSUE THREAD

**Issue by antonbrams** [xixixao/stacked-tabs#1]
By enabling of the plugin the tab bar gets hidden.

**Comment by antonbrams** [comment]
i think i know why it happens. I'm using my own theme where all the tabs are taking the whole width of the pane. So may be because of the css style collision all the tabs are disappearing. Is it possible to add a functionality to this plugin so that it behaves as tabs in the safari app (stretch tabs to the max width)?

**Comment by xixixao** [comment]
The point of this plugin is that tabs take the least amount of space needed. I would suggest changing your theme if you want to use it.

I would be happy to look at a PR if you figure out how to maximize the tabs when there is space.

Thanks for giving the plugin a try!
